# PR Checks File for checking PR commits meet our requirements.
name: PR Checks

on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  pr-checks:
    # ubuntu-latest was original
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: clean install dependencies. Fail on lockfile Changes.
        run: yarn install --immutable --immutable-cache --check-cache

      - name: run eslint
        run: yarn eslint

      - name: run prettier
        run: yarn prettier

      - name: run tests
        run: yarn test
